# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = [
  "github.com/hashicorp/terraform/backend*",
  "github.com/terraform-providers/terraform-provider-aws/github.com/hashicorp/nomad*"
]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.82"

[[constraint]]
  name = "github.com/beevik/etree"
  version = "1.0.1"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/hashicorp/go-cleanhttp"
  version = "0.5.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.9-beta1"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.4"

[[constraint]]
  name = "github.com/jen20/awspolicyequivalence"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/copystructure"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/pquerna/otp"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-template"
  version = "0.1.1"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-tls"
  version = "0.1.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
